name: Generate Snake
 
on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  push:
    branches:
      - master # or the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3 # Updated to use the latest version

      - name: Generate snake animation
        uses: Platane/snk@v2.2.0
        with:
          github_user_name: aviralgarg05
          outputs: dist/snake.svg

      - name: Push the SVG to the repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
